/** @format */

import theme from "../Theme/Theme";

export const Style: any = {
    image: {
        width: '100%',
        height: '100%',
        borderRadius: '10px',
        display: 'flex',
        justifyContent: "space-evenly",
    },
    id: {
        // position:'absolute',
        width: '100%',
        height: '100%',
        fontFamily: 'Inter !important',
        fontStyle: 'normal !important',
        fontWeight: '700 !important',
        fontSize: '22px !important',
        lineHeight: '40px !important',
        color: '#000620',
        marginTop:'20px !important',
    },
    time: {
        width: '100%',
        height: '100%',
        fontFamily: 'Inter !important',
        fontStyle: 'normal !important',
        fontWeight: '700 !important',
        fontSize: '17px !important',
        lineHeight: '40px !important',
        color: '#1C97FD',
        marginTop:'20px !important', 
    },
    delivered:{
        width: '100%',
        height: '100%',
        fontFamily: 'Inter !important',
        fontStyle: 'normal !important',
        fontWeight: '700 !important',
        fontSize: '17px !important',
        lineHeight: '40px !important',
        color: '#1C97FD',
        marginTop:'20px !important',  
    },
    address:{
        width: '100%',
        height: '100%',
        fontFamily: 'Inter !important',
        fontStyle: 'normal !important',
        fontWeight: '700 !important',
        fontSize: '17px !important',
        lineHeight: '26px !important',
        color: '#A2A3A5',
        marginTop:'20px !important', 
    },
    Rs:{
        width: '100%',
        height: '100%',
        fontFamily: 'Inter !important',
        fontStyle: 'normal !important',
        fontWeight: '700 !important',
        fontSize: '18px !important',
        lineHeight: '26px !important',
        color: '#1C97FD',
        marginTop:'20px !important', 
    },
    line: {
		width: "2px",
		height: "20px",
		background: "#D9D9D9",
		// marginRight: "10px !important",
        margin:'auto !important',
        marginTop:'25px !important', 
	},
};
